#!/bin/sh
# AutoSE installer (macOS / Linux)
# Clones the AutoSE repo, builds it, and links the `autose` CLI onto your PATH.
#
#   curl -fsSL https://autose-labs.github.io/autose/install.sh | sh
#
# Honors these environment variables:
#   AUTOSE_HOME     where to clone AutoSE        (default: $HOME/.autose-cli)
#   AUTOSE_BIN_DIR  where to place the launcher  (default: $HOME/.local/bin)
#   AUTOSE_REF      git ref to check out         (default: poc)

set -eu

REPO_URL="https://github.com/AutoSE-Labs/autose.git"
INSTALL_DIR="${AUTOSE_HOME:-$HOME/.autose-cli}"
BIN_DIR="${AUTOSE_BIN_DIR:-$HOME/.local/bin}"
REF="${AUTOSE_REF:-poc}"

# Pretty output
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  BOLD=$(printf '\033[1m'); DIM=$(printf '\033[2m'); RESET=$(printf '\033[0m')
  INK=$(printf '\033[38;5;24m'); SIGNAL=$(printf '\033[38;5;166m')
else
  BOLD=""; DIM=""; RESET=""; INK=""; SIGNAL=""
fi
say()  { printf '%s\n' "$*"; }
step() { printf '%s>%s %s\n' "$SIGNAL" "$RESET" "$*"; }
die()  { printf '%serror:%s %s\n' "$SIGNAL" "$RESET" "$*" >&2; exit 1; }

say ""
say "${BOLD}${INK}AutoSE${RESET}  sovereign autonomous software engineering"
say "${DIM}local-first, org-aware, zero cloud${RESET}"
say ""

# Prerequisites
command -v git >/dev/null 2>&1 || die "git is required but was not found. Install it from https://git-scm.com"
command -v node >/dev/null 2>&1 || die "Node.js 20 or newer is required but was not found. Install it from https://nodejs.org"
command -v npm >/dev/null 2>&1 || die "npm is required but was not found. It ships with Node.js (https://nodejs.org)"

NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)
[ "$NODE_MAJOR" -ge 20 ] 2>/dev/null || die "Node.js 20 or newer is required (found $(node -v)). Upgrade at https://nodejs.org"

# Fetch
if [ -d "$INSTALL_DIR/.git" ]; then
  step "Updating AutoSE in $INSTALL_DIR"
  git -C "$INSTALL_DIR" fetch --depth 1 origin "$REF" >/dev/null 2>&1
  git -C "$INSTALL_DIR" checkout -q "$REF"
  git -C "$INSTALL_DIR" reset --hard -q "origin/$REF" 2>/dev/null || git -C "$INSTALL_DIR" pull -q
else
  [ -e "$INSTALL_DIR" ] && die "$INSTALL_DIR already exists but is not a git checkout. Remove it or set AUTOSE_HOME."
  step "Cloning AutoSE into $INSTALL_DIR"
  git clone --depth 1 --branch "$REF" "$REPO_URL" "$INSTALL_DIR" >/dev/null 2>&1 \
    || git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" >/dev/null 2>&1 \
    || die "Failed to clone $REPO_URL"
fi

# Build
step "Installing dependencies (this can take a minute)"
( cd "$INSTALL_DIR" && npm install --no-audit --no-fund >/dev/null 2>&1 ) || die "npm install failed. Run it manually in $INSTALL_DIR to see the error."

step "Building AutoSE"
( cd "$INSTALL_DIR" && npm run build >/dev/null 2>&1 ) || die "Build failed. Run 'npm run build' in $INSTALL_DIR to see the error."

# Link the launcher
step "Linking the autose launcher into $BIN_DIR"
mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/autose"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# AutoSE launcher, generated by install.sh
exec "$INSTALL_DIR/bin/autose" "\$@"
EOF
chmod +x "$LAUNCHER"

# Done
say ""
say "${BOLD}AutoSE is installed.${RESET}"
say ""

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    say "${SIGNAL}One more step.${RESET} $BIN_DIR is not on your PATH yet."
    say "Add this line to your shell profile (~/.zshrc, ~/.bashrc, and so on):"
    say ""
    say "    ${BOLD}export PATH=\"$BIN_DIR:\$PATH\"${RESET}"
    say ""
    ;;
esac

say "Next steps:"
say "  1. Install and start Ollama       ${DIM}https://ollama.com${RESET}"
say "     ${DIM}ollama pull llama3.2 && ollama pull qwen2.5-coder:14b${RESET}"
say "  2. Initialize a workspace         ${BOLD}autose init --workspace .${RESET}"
say "  3. Start engineering              ${BOLD}autose chat --workspace .${RESET}"
say ""
