from __future__ import annotations

import sys
from pathlib import Path
from typing import Protocol, Union

import yaml

_CODE_DIR = Path(__file__).resolve().parents[2]
_LOGIC_DIR = _CODE_DIR / "logic"
if str(_LOGIC_DIR) not in sys.path:
    sys.path.insert(0, str(_LOGIC_DIR))


class StandardRunClient(Protocol):
    """Client hooks used by the core standard workflow."""

    def prepare_agent(self, agent: object) -> None:
        """Apply client-specific instrumentation to an agent."""

    def build_session_context(self, call_fn) -> list[dict] | None:
        """Return prior session context for agent prompts."""

    def record_memory_exchange(self, prompt: str, assistant: str) -> None:
        """Persist the completed exchange in client/session memory."""

    def start_stage(self, stage: str, title: str, thinking_label: str) -> None:
        """Notify the client that a workflow stage has started."""

    def stream_assistant_chunk(self, chunk: str) -> None:
        """Render or capture an assistant streaming chunk."""

    def finish_streaming(self) -> None:
        """Notify the client that the current streaming response is complete."""

    def add_assistant_message(self, message: str) -> None:
        """Append a complete assistant message."""

    def request_plan_review(self) -> str:
        """Ask the user/client for plan approval or revision feedback."""

    def add_user_message(self, message: str) -> None:
        """Append a user-originated message generated by the workflow."""

    def capture_file_update(self, path: str, old_text: str, new_text: str) -> None:
        """Record a file update artifact and display diff if desired."""

    def add_artifact(
        self,
        kind: str,
        title: str,
        *,
        path: str = "",
        content: str = "",
        **metadata,
    ) -> None:
        """Record a structured artifact."""

    def note_test(self, name: str, status: str, details: str = "") -> None:
        """Record a test or validation result."""

    def complete(self, summary: str) -> None:
        """Mark the task session complete."""

    def fail(self, message: str) -> None:
        """Mark the task session failed."""

    def reset_activity(self) -> None:
        """Clear client activity indicators after completion or failure."""


class StandardRunner:
    """Core Plan -> Code -> Test runner, independent of terminal rendering."""

    def __init__(
        self,
        config_path: Union[str, Path],
        workspace_root: Union[str, Path],
        client: StandardRunClient,
    ) -> None:
        self.config_path = Path(config_path)
        self.workspace_root = Path(workspace_root)
        self.client = client

    def run(self, prompt: str) -> None:
        from standard.code.agent import CodeAgent
        from standard.code.tools import TOOLS as CODE_TOOLS
        from standard.plan.agent import PlanAgent
        from standard.test.agent import TestAgent

        with open(self.config_path, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f)

        inference = config.get("inference", {})
        kwargs = dict(
            base_url=inference.get("base_url", "http://127.0.0.1:11434/v1"),
            api_key=inference.get("api_key", "") or "",
            model=inference.get("model", ""),
            workspace_root=str(self.workspace_root),
        )

        try:
            self.client.start_stage("plan", "Plan", "Planning")
            plan_agent = PlanAgent(**kwargs)
            self.client.prepare_agent(plan_agent)

            session_context = self.client.build_session_context(plan_agent._call_sync)

            plan = self._stream_plan(plan_agent, prompt, session_context, show=False)
            
            artifact_path = Path(self.workspace_root) / ".autose" / "artifacts" / "plan.md"
            artifact_path.parent.mkdir(parents=True, exist_ok=True)
            artifact_path.write_text(plan, encoding="utf-8")
            self.client.add_assistant_message(f"Implementation Plan written to `{artifact_path.relative_to(self.workspace_root)}`")
            
            self.client.add_artifact("plan", "Implementation plan", content=plan)

            plan = self._review_plan(prompt, plan, kwargs, PlanAgent)

            self.client.start_stage("code", "Code", "Implementing")
            code_agent = CodeAgent(**kwargs)
            self.client.prepare_agent(code_agent)

            orig_write = CODE_TOOLS["write_file"].fn
            orig_edit = CODE_TOOLS["edit_file"].fn
            CODE_TOOLS["write_file"].fn = self._patched_write_file(orig_write)
            CODE_TOOLS["edit_file"].fn = self._patched_edit_file(orig_edit)

            try:
                code_summary = code_agent.run(prompt, plan)
            finally:
                CODE_TOOLS["write_file"].fn = orig_write
                CODE_TOOLS["edit_file"].fn = orig_edit

            self.client.add_assistant_message(code_summary)
            self.client.add_artifact("summary", "Code summary", content=code_summary)

            self.client.start_stage("test", "Test", "Testing")
            test_agent = TestAgent(**kwargs)
            self.client.prepare_agent(test_agent)

            test_chunks: list[str] = []
            for chunk in test_agent.run(prompt, plan, code_summary):
                self.client.stream_assistant_chunk(chunk)
                test_chunks.append(chunk)

            self.client.record_memory_exchange(prompt, code_summary)
            test_output = "".join(test_chunks)
            if test_output:
                self.client.add_artifact(
                    "test_output",
                    "Test output",
                    content=test_output,
                )
                self.client.note_test(
                    "standard_pipeline",
                    "completed",
                    details=test_output[:500],
                )
            self.client.complete(code_summary)
        except Exception as exc:
            self.client.fail(f"Pipeline error: {exc}")
            self.client.add_assistant_message(f"Pipeline error: {exc}")
        finally:
            self.client.reset_activity()

    def _stream_plan(
        self,
        plan_agent: object,
        prompt: str,
        session_context: list[dict] | None,
        show: bool = True,
    ) -> str:
        plan_chunks: list[str] = []
        for chunk in plan_agent.run(prompt, session_context=session_context):
            if show:
                self.client.stream_assistant_chunk(chunk)
            plan_chunks.append(chunk)
        if show:
            self.client.finish_streaming()
        return "".join(plan_chunks)

    def _review_plan(self, prompt: str, plan: str, kwargs: dict, plan_cls) -> str:
        while True:
            feedback = self.client.request_plan_review()
            if feedback.lower() in ("a", "approve", "y", "yes", ""):
                self.client.add_user_message("Approved \u2713")
                return plan

            self.client.add_user_message(feedback)
            self.client.start_stage("plan", "Plan (revised)", "Re-planning")

            rev_agent = plan_cls(**kwargs)
            self.client.prepare_agent(rev_agent)

            plan_chunks: list[str] = []
            for chunk in rev_agent.run(prompt, previous_plan=plan, feedback=feedback):
                plan_chunks.append(chunk)

            plan = "".join(plan_chunks)
            
            artifact_path = Path(self.workspace_root) / ".autose" / "artifacts" / "plan.md"
            artifact_path.parent.mkdir(parents=True, exist_ok=True)
            artifact_path.write_text(plan, encoding="utf-8")
            self.client.add_assistant_message(f"Revised Implementation Plan written to `{artifact_path.relative_to(self.workspace_root)}`")
            
            self.client.add_artifact(
                "plan",
                "Revised implementation plan",
                content=plan,
            )

    def _patched_write_file(self, original_fn):
        def wrapper(**kwargs) -> str:
            path = kwargs.get("path")
            content = kwargs.get("content")
            if path is None:
                return "Error: missing required argument 'path'"
            if content is None:
                return "Error: missing required argument 'content'"
            
            p = Path(path)
            old_text = p.read_text(encoding="utf-8") if p.exists() and p.is_file() else ""
            result = original_fn(**kwargs)
            self.client.capture_file_update(path, old_text, content)
            return result

        return wrapper

    def _patched_edit_file(self, original_fn):
        def wrapper(**kwargs) -> str:
            path = kwargs.get("path")
            old_str = kwargs.get("old_str")
            new_str = kwargs.get("new_str")
            if path is None:
                return "Error: missing required argument 'path'"
            if old_str is None:
                return "Error: missing required argument 'old_str'"
            if new_str is None:
                return "Error: missing required argument 'new_str'"
            
            p = Path(path)
            old_text = p.read_text(encoding="utf-8") if p.exists() and p.is_file() else ""
            result = original_fn(**kwargs)
            new_text = (
                p.read_text(encoding="utf-8")
                if p.exists() and p.is_file()
                else old_text
            )
            self.client.capture_file_update(path, old_text, new_text)
            return result

        return wrapper
